# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-04-29 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0003_tenant_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lifetime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registertime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenantid',
            field=models.CharField(default=b'00000000000000', max_length=14, unique=True),
        ),
    ]
