# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-04-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0005_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='tenantId',
            field=models.CharField(default=b'0000000000', max_length=14),
        ),
    ]
