# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0006_auto_20160429_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='schema',
            name='usedcap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenantid',
            field=models.CharField(default=b'00000000000000', max_length=17, unique=True),
        ),
    ]
