# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0007_auto_20160516_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenantid',
            field=models.CharField(default=b'00000000000000', max_length=19, unique=True),
        ),
    ]
