# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-16 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0010_auto_20160516_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='endtime',
            field=models.CharField(default=b'0000000000', max_length=10),
        ),
    ]
