# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0011_auto_20160516_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default=b'admin', max_length=20),
        ),
    ]
